### ISSUE TITLE
Формирования состава чека

### ISSUE THREAD

**Issue by perevoshchikov** [flowwow/cloudpayments-php-client#1]
Привет. 
Планируете добавить билдер/dto для состава чека? Не хочется руками собирать [массив](https://github.com/flowwow/cloudpayments-php-client/blob/main/src/Request/KktReceipt.php#L26) при создании чека.
@see https://developers.cloudkassir.ru/#customerreceipt

**Comment by freefess** [comment]
@perevoshchikov да, следующая доработка как раз набор dto для чеков будет

**Comment by freefess** [comment]
Поддержку dto для чеков добавили
